### Load Modules

In [98]:
# Load simulator libraries
from Libraries.Qbits import QBit

# Load python libraries
import numpy as np

In [99]:
# Run the simulator module
# Just for testing
%run Libraries/Qbits.py

The module allows to create and manage quantum bits.


### Qbit declaration and representation

In [100]:
# Create a qbit
q = QBit()

# Print the qbit
print(q)

# Represent the qbit
q

A QBit with angle 0.0π and phase 0.0π.


QBit(0.0,0.0)

In [101]:
# Represent the qbit as a vector
q.as_vector()

array([[1.+0.j],
       [0.+0.j]])

In [102]:
# Define a qbit given its vector representation
# Useful (maybe) when applying gates
q1 = QBit.from_vector(q.as_vector())
q1

QBit(0.0,0.0)

### Qbit measurement

In [103]:
# Measure the qbit
# After the measurement, the qbit parameters are updated
# to the measured state.
q.measure()

0

In [104]:
# Measure the qbit and print its state
q.get_state()

The qbit is in the |0> state


### Qbit manipulation

In [105]:
# Manipulate the qbit

# For now, we directly access the qbit attributes.
# This sould become deprecated once the simulator
# gets more developed.
q.theta = np.pi
q.phi = np.pi / 2

# Check if the changes have happened
print(q)

# Measure the qbit and print its state
q.get_state()
print(q.theta)
print(q.phi)

A QBit with angle 1.0π and phase 0.5π.
The qbit is in the |1> state
3.14159265
0


### 1-qbit gates

In [107]:
# Apply a x-gate
q = QBit()
print(q)
q.get_state()
print(q.as_vector())
print()

q.x_gate()
print(q)
q.get_state()
print(q.as_vector())
print()

q.x_gate()
print(q)
q.get_state()
print(q.as_vector())
print()

A QBit with angle 0.0π and phase 0.0π.
The qbit is in the |0> state
[[1.+0.j]
 [0.+0.j]]

A QBit with angle 1.0π and phase 0.0π.
The qbit is in the |1> state
[[0.+0.j]
 [1.+0.j]]

A QBit with angle 0.0π and phase 0.0π.
The qbit is in the |0> state
[[1.+0.j]
 [0.+0.j]]



In [108]:
# Apply a hadamard gate on a qbit in the |0> state
q = QBit()
q.get_state()
print()

print(q)
print(q.as_vector())
print()

q.h_gate()
print(q)
print(q.as_vector())
print()

q.h_gate()
print(q)
print(q.as_vector())
print()

The qbit is in the |0> state

A QBit with angle 0.0π and phase 0.0π.
[[1.+0.j]
 [0.+0.j]]

A QBit with angle 0.5π and phase 0.0π.
[[0.70710678+0.j]
 [0.70710678+0.j]]

A QBit with angle 0.0π and phase 0.0π.
[[1.+0.j]
 [0.+0.j]]



In [109]:
# Apply a hadamard gate on a qbit in the |1> state

q = QBit()
q.x_gate()
q.get_state()
print()

print(q)
print(q.as_vector())
print()

q.h_gate()
print(q)
print(q.as_vector())
print()

q.h_gate()
print(q)
print(q.as_vector())
print()

The qbit is in the |1> state

A QBit with angle 1.0π and phase 0.0π.
[[0.+0.j]
 [1.+0.j]]

A QBit with angle 0.5π and phase 1.0π.
[[ 0.70710678+0.j]
 [-0.70710678+0.j]]

A QBit with angle 1.0π and phase 0.0π.
[[0.+0.j]
 [1.+0.j]]



In [110]:
# Apply a u1 gate

q = QBit()
q.h_gate()
print(q)

# lambda angle
l = PI/4

q.u1_gate(l)
print(q)
q.as_vector()

A QBit with angle 0.5π and phase 0.0π.
A QBit with angle 0.5π and phase 0.25π.


array([[0.70710678+0.j ],
       [0.5       +0.5j]])

In [111]:
# Apply a u2 gate

q = QBit()
q.h_gate()
print(q)

# lambda angle
l = PI/4
# phi angle
p = PI/2

q.u2_gate(l,p)
print(q)
q.as_vector()

A QBit with angle 0.5π and phase 0.0π.
A QBit with angle 0.5π and phase 0.75π.


array([[ 0.70710678+0.j ],
       [-0.5       +0.5j]])

In [112]:
# Apply a u3 gate

q = QBit()
q.h_gate()
print(q)

# lambda angle
l = PI/4
# phi angle
p = PI/2
# theta angle
t = PI

q.u3_gate(l,t,p)
print(q)
q.as_vector()

A QBit with angle 0.5π and phase 0.0π.
A QBit with angle 0.71π and phase 0.5π.


array([[ 0.43701602+0.j        ],
       [-0.        +0.89945372j]])

### Controlled gates

In [113]:
# Apply a c-not gate: |00> --> |00>

q1 = QBit()
print("q1:")
q1.get_state()

q2 = QBit()
print("q2:")
q2.get_state()

print()
print("Applying c-not gate...")
print()

q1.c_not_gate(q2)

print("q1:")
q1.get_state()
print("q2:")
q2.get_state()

q1:
The qbit is in the |0> state
q2:
The qbit is in the |0> state

Applying c-not gate...

q1:
The qbit is in the |0> state
q2:
The qbit is in the |0> state


In [114]:
# Apply a c-not gate: |01> --> |01>

q1 = QBit()
print("q1:")
q1.get_state()

q2 = QBit()
q2.x_gate()
print("q2:")
q2.get_state()

print()
print("Applying c-not gate...")
print()

q1.c_not_gate(q2)

print("q1:")
q1.get_state()
print("q2:")
q2.get_state()

q1:
The qbit is in the |0> state
q2:
The qbit is in the |1> state

Applying c-not gate...

q1:
The qbit is in the |0> state
q2:
The qbit is in the |1> state


In [115]:
# Apply a c-not gate: |10> --> |11>

q1 = QBit()
q1.x_gate()
print("q1:")
q1.get_state()

q2 = QBit()
print("q2:")
q2.get_state()

print()
print("Applying c-not gate...")
print()

q1.c_not_gate(q2)

print("q1:")
q1.get_state()
print("q2:")
q2.get_state()

q1:
The qbit is in the |1> state
q2:
The qbit is in the |0> state

Applying c-not gate...

q1:
The qbit is in the |1> state
q2:
The qbit is in the |1> state


In [116]:
# Apply a c-not gate: |11> --> |10>

q1 = QBit()
q1.x_gate()
print("q1:")
q1.get_state()

q2 = QBit()
q2.x_gate()
print("q2:")
q2.get_state()

print()
print("Applying c-not gate...")
print()

q1.c_not_gate(q2)

print("q1:")
q1.get_state()
print("q2:")
q2.get_state()

q1:
The qbit is in the |1> state
q2:
The qbit is in the |1> state

Applying c-not gate...

q1:
The qbit is in the |1> state
q2:
The qbit is in the |0> state


In [117]:
# Apply a c-hadamard gate: |10> --> |11> + |10>

q1 = QBit()
q1.x_gate()
print("q1:")
q1.get_state()

q2 = QBit()
print("q2:")
q2.get_state()

print()
print("Applying c-hadamard gate...")
print()

q1.c_h_gate(q2)

print("q1:")
q1.get_state()
print("q2:")
print(q2)
q2.get_state()

q1:
The qbit is in the |1> state
q2:
The qbit is in the |0> state

Applying c-hadamard gate...

q1:
The qbit is in the |1> state
q2:
A QBit with angle 0.5π and phase 0.0π.
The qbit is in the |1> state


### Circuits

Idea: 
- define a new Circuit object;
- assign to each gate a number;
- for each gate, append the corresponding number and eventual parameters to a list of instructions;
- execute the circuit by reading the list and applying the corresponding gates with the correct parameters.